export const HOME_PAGE__GET_LATEST_ADDS_REQUEST =
    "HOME_PAGE__GET_LATEST_ADDS_REQUEST",
  HOME_PAGE__GET_LATEST_ADDS_SUCCESS = "HOME_PAGE__GET_LATEST_ADDS_SUCCESS",
  HOME_PAGE__GET_LATEST_ADDS_FAILURE = "HOME_PAGE__GET_LATEST_ADDS_FAILURE",
  HOME_PAGE__GET_LATEST_CATEGORY_ADDS_REQUEST =
    "HOME_PAGE__GET_LATEST_CATEGORY_ADDS_REQUEST",
  HOME_PAGE__GET_LATEST_CATEGORY_ADDS_SUCCESS =
    "HOME_PAGE__GET_LATEST_CATEGORY_ADDS_SUCCESS",
  HOME_PAGE__GET_LATEST_CATEGORY_ADDS_FAILURE =
    "HOME_PAGE__GET_LATEST_CATEGORY_ADDS_FAILURE",
  HOME_PAGE__SEND_MESSAGE_TO_OWNER_REQUEST =
    "HOME_PAGE__SEND_MESSAGE_TO_OWNER_REQUEST",
  HOME_PAGE__SEND_MESSAGE_TO_OWNER_SUCCESS =
    "HOME_PAGE__SEND_MESSAGE_TO_OWNER_SUCCESS",
  HOME_PAGE__SEND_MESSAGE_TO_OWNER_FAILURE =
    "HOME_PAGE__SEND_MESSAGE_TO_OWNER_FAILURE",
  HOME_PAGE__DELETE_MESSAGE_NOTIFICATION =
    "HOME_PAGE__DELETE_MESSAGE_NOTIFICATION";
