module.exports = {
  VERIFIED: "VERIFIED",
  INITIATED: "INITIATED",
  SMS_OTP: "SMS_OTP",
  EMAIL: "EMAIL",
  LOCAL: "local",
  FACEBOOK: "facebook",
  GOOGLE: "google",
  TWITTER: "twitter",
  INITIATED: "INITIATED",
  INITIATED_EMAIL_OTP: "INITIATED_EMAIL_OTP",
  INITIATED_SMS_OTP: "INITIATED_SMS_OTP",
  PENDING: "PENDING",
  VERIFIED: "VERIFIED",
  SMS_OTP: "SMS_OTP",
  EMAIL: "EMAIL",
  GUEST: "GUEST",
  DEFAULT: "DEFAULT",
  RENTEE: "RENTEE",
  RENTER: "RENTER",
  ADMIN: "ADMIN",
  ROOT: "ROOT",
  INVALID: "INVALID",
  VALID: "VALID",
  BLOCKED: "BLOCKED",
  BLACKLISTED: "BLACKLISTED",
  NULL: "NULL",
  SOCIAL_MEDIA: "SOCIAL_MEDIA",
  VERIFICATION: "VERIFICATION",
  SUCCESS: "SUCCESS",
  FAILURE: "FAILURE",
  ERROR: "ERROR",
  SENT: "SENT",
  USED: "USED",
  RESEND: "RESEND",
  NOT_INITIATED: "NOT_INITIATED",
  UPDATE: "UPDATE",
  HYUNDAI: "HYUNDAI",
  TATA: "TATA",
  MAHINDRA: "MAHINDRA",
  SUZUKI: "SUZUKI",
  KIA: "KIA",
  TOYOTA: "TOYOTA",
  SKODA: "SKODA",
  BMW: "BMW",
  HONDA: "HONDA",
  FORD: "FORD",
  AUDI: "AUDI",
  VOLKSWAGEN: "VOLKSWAGEN",
  RENAULT: "RENAULT",
  MERCEDES_BENZ: "MERCEDES_BENZ",
  JEEP: "JEEP",
  MG: "MG",
  NISSAN: "NISSAN",
  JAGUAR: "JAGUAR",
  VOLVO: "VOLVO",
  LAND_ROVER: "LAND_ROVER",
  LAMBORGHINI: "LAMBORGHINI",
  PORSHE: "PORSHE",
  MCLAREN: "MCLAREN",
  LEXUS: "LEXUS",
  MINI: "MINI",
  TESLA: "TESLA",
  ROLLS_ROYCE: "ROLLS_ROYCE",
  ISUZU: "ISUZU",
  DATSUN: "DATSUN",
  FERRARI: "FERRARI",
  CITROEN: "CITROEN",
  BENTLEY: "BENTLEY",
  MITSUBISHI: "MITSUBISHI",
  MASERATI: "MASERATI",
  BUGATTI: "BUGATTI",
  HAVAL: "HAVAL",
  FORCE_MOTORS: "FORCE_MOTORS",
  ASTON_MARTIN: "ASTON_MARTIN",
  HATCHBACK: "HATCHBACK",
  SEDAN: "SEDAN",
  SUV: "SUV",
  CROSSOVER: "CROSSOVER",
  COUPE: "COUPE",
  CONVERTIBLE: "CONVERTIBLE",
  MANUAL: "MANUAL",
  AUTOMATIC: "AUTOMATIC",
  PETROL: "PETROL",
  DEISEL: "DEISEL",
  PENDING_VERIFICATION: "PENDING_VERIFICATION",
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
  ELECTRIC: "ELECTRIC",
  HYBRID: "HYBRID",
  DRAFT: "DRAFT",
  FURNITURE: "FURNITURE",
  SOFA: "SOFA",
  SINGLE: "SINGLE",
  SOFA_SET: "SOFA_SET",
  LEATHER: "LEATHER",
  COTTON: "COTTON",
  LINEN: "LINEN",
  SILK: "SILK",
  VELVET: "VELVET",
  AVERAGE: "AVERAGE",
  EXCELLENT: "EXCELLENT",
  GOOD: "GOOD",
  DAYS: "DAYS",
  WEEKS: "WEEKS",
  MONTHS: "MONTHS",
  YEARS: "YEARS",
  DOLLAR: "DOLLAR",
  EURO: "EURO",
  DAY: "DAY",
  WEEK: "WEEK",
  MONTH: "MONTH",
  YEAR: "YEAR",
  RESTAURANT: "RESTAURANT",
  STUDY: "STUDY",
  DINING: "DINING",
  WOOD: "WOOD",
  IRON: "IRON",
  ALUMINIUM: "ALUMINIUM",
  SQUARE: "SQUARE",
  ROUND: "ROUND",
  RECTANGLE: "RECTANGLE",
  TABLE: "TABLE",
  PROCESSING: "PROCESSING",
  RENTED: "RENTED",
  NOT_RENTED: "NOT_RENTED",
  ALLOWED_MOBILE_COUNTRIES: [
    "am-Am",
    "ar-AE",
    "ar-BH",
    "ar-DZ",
    "ar-EG",
    "ar-IQ",
    "ar-JO",
    "ar-KW",
    "ar-SA",
    "ar-SY",
    "ar-TN",
    "az-AZ",
    "az-LY",
    "az-LB",
    "bs-BA",
    "be-BY",
    "bg-BG",
    "bn-BD",
    "ca-AD",
    "cs-CZ",
    "da-DK",
    "de-DE",
    "de-AT",
    "de-CH",
    "de-LU",
    "el-GR",
    "en-AU",
    "en-CA",
    "en-GB",
    "en-GG",
    "en-GH",
    "en-HK",
    "en-MO",
    "en-IE",
    "en-IN",
    "en-KE",
    "en-MT",
    "en-MU",
    "en-NG",
    "en-NZ",
    "en-PK",
    "en-PH",
    "en-RW",
    "en-SG",
    "en-SL",
    "en-UG",
    "en-US",
    "en-TZ",
    "en-ZA",
    "en-ZM",
    "en-ZW",
    "es-AR",
    "es-BO",
    "es-CL",
    "es-CO",
    "es-CR",
    "es-DO",
    "es-HN",
    "es-PE",
    "es-EC",
    "es-ES",
    "es-MX",
    "es-PA",
    "es-PY",
    "es-UY",
    "et-EE",
    "fa-IR",
    "fi-FI",
    "fj-FJ",
    "fo-FO",
    "fr-BE",
    "fr-FR",
    "fr-GF",
    "fr-GP",
    "fr-MQ",
    "fr-RE",
    "ga-IE",
    "he-IL",
    "hu-HU",
    "id-ID",
    "it-IT",
    "it-SM",
    "ja-JP",
    "ka-GE",
    "kk-KZ",
    "kl-GL",
    "ko-KR",
    "lt-LT",
    "ms-MY",
    "mz-MZ",
    "nb-NO",
    "ne-NP",
    "nl-BE",
    "nl-NL",
    "nn-NO",
    "pl-PL",
    "pt-BR",
    "pt-PT",
    "pt-AO",
    "ro-RO",
    "ru-RU",
    "si-LK",
    "sl-SI",
    "sk-SK",
    "sq-AL",
    "sr-RS",
    "sv-SE",
    "th-TH",
    "tr-TR",
    "uk-UA",
    "uz-UZ",
    "vi-VN",
    "zh-CN",
    "zh-HK",
    "zh-MO",
    "zh-TW",
  ],
};
