export const FORGOT_PASSWORD__CHECK_EMAIL_ID_REQUEST =
		"FORGOT_PASSWORD__CHECK_EMAIL_ID_REQUEST",
	FORGOT_PASSWORD__CHECK_EMAIL_ID_SUCCESS =
		"FORGOT_PASSWORD__CHECK_EMAIL_ID_SUCCESS",
	FORGOT_PASSWORD__CHECK_EMAIL_ID_FAILURE =
		"FORGOT_PASSWORD__CHECK_EMAIL_ID_FAILURE",
	FORGOT_PASSWORD__CHECK_CHALLENGE_CODE_REQUEST =
		"FORGOT_PASSWORD__CHECK_CHALLENGE_CODE_REQUEST",
	FORGOT_PASSWORD__CHECK_CHALLENGE_CODE_SUCCESS =
		"FORGOT_PASSWORD__CHECK_CHALLENGE_CODE_SUCCESS",
	FORGOT_PASSWORD__CHECK_CHALLENGE_CODE_FAILURE =
		"FORGOT_PASSWORD__CHECK_CHALLENGE_CODE_FAILURE",
	FORGOT_PASSWORD__UPDATE_PASSWORD_REQUEST =
		"FORGOT_PASSWORD__UPDATE_PASSWORD_REQUEST",
	FORGOT_PASSWORD__UPDATE_PASSWORD_SUCCESS =
		"FORGOT_PASSWORD__UPDATE_PASSWORD_SUCCESS",
	FORGOT_PASSWORD__UPDATE_PASSWORD_FAILURE =
		"FORGOT_PASSWORD__UPDATE_PASSWORD_FAILURE",
	FORGOT_PASSWORD__CLEAR_DATA = "FORGOT_PASSWORD__CLEAR_DATA";
