export const PROFILE__UPDATE_USER_INFO_REQUEST =
		"PROFILE__UPDATE_USER_INFO_REQUEST",
	PROFILE__UPDATE_USER_INFO_SUCCESS = "PROFILE__UPDATE_USER_INFO_SUCCESS",
	PROFILE__UPDATE_USER_INFO_FAILURE = "PROFILE__UPDATE_USER_INFO_FAILURE",
	PROFILE__CHANGE_USER_PASSWORD_REQUEST =
		"PROFILE__CHANGE_USER_PASSWORD_REQUEST",
	PROFILE__CHANGE_USER_PASSWORD_SUCCESS =
		"PROFILE__CHANGE_USER_PASSWORD_SUCCESS",
	PROFILE__CHANGE_USER_PASSWORD_FAILURE =
		"PROFILE__CHANGE_USER_PASSWORD_FAILURE",
	PROFILE__CHANGE_USER_MOBILE_NUMBER_REQUEST =
		"PROFILE__CHANGE_USER_MOBILE_NUMBER_REQUEST",
	PROFILE__CHANGE_USER_MOBILE_NUMBER_SUCCESS =
		"PROFILE__CHANGE_USER_MOBILE_NUMBER_SUCCESS",
	PROFILE__CHANGE_USER_MOBILE_NUMBER_FAILURE =
		"PROFILE__CHANGE_USER_MOBILE_NUMBER_FAILURE",
	PROFILE__CLEAR_DATA = "PROFILE__CLEAR_DATA",
	PROFILE__UPDATE_USER_AVATAR_REQUEST = "PROFILE__UPDATE_USER_AVATAR_REQUEST",
	PROFILE__UPDATE_USER_AVATAR_SUCCESS = "PROFILE__UPDATE_USER_AVATAR_SUCCESS",
	PROFILE__UPDATE_USER_AVATAR_FAILURE = "PROFILE__UPDATE_USER_AVATAR_FAILURE";
