export const USER_TOKEN_LOGIN_REQUEST = "USER_TOKEN_LOGIN_REQUEST";
export const USER_TOKEN_LOGIN_SUCCESS = "USER_TOKEN_LOGIN_SUCCESS";
export const USER_TOKEN_LOGIN_FAILURE = "USER_TOKEN_LOGIN_FAILURE";
export const USER_TOKEN_LOGIN_SUCCESS_SIGNUP_PENDING =
	"USER_LOGIN_SUCCESS_SIGNUP_PENDING";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_SUCCESS_SIGNUP_PENDING =
	"USER_LOGIN_SUCCESS_SIGNUP_PENDING";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";
