export const MY_ORDERS__CART__ADD_PRODUCT_REQUEST =
    "MY_ORDERS__CART__ADD_PRODUCT_REQUEST",
  MY_ORDERS__CART__ADD_PRODUCT_SUCCESS = "MY_ORDERS__CART__ADD_PRODUCT_SUCCESS",
  MY_ORDERS__CART__ADD_PRODUCT_FAILURE = "MY_ORDERS__CART__ADD_PRODUCT_FAILURE",
  MY_ORDERS__CART__GET_ALL_PRODUCTS_REQUEST =
    "MY_ORDERS__CART__GET_ALL_PRODUCTS_REQUEST",
  MY_ORDERS__CART__GET_ALL_PRODUCTS_SUCCESS =
    "MY_ORDERS__CART__GET_ALL_PRODUCTS_SUCCESS",
  MY_ORDERS__CART__GET_ALL_PRODUCTS_FAILURE =
    "MY_ORDERS__CART__GET_ALL_PRODUCTS_FAILURE",
  MY_ORDERS__CART__REMOVE_PRODUCT_REQUEST =
    "MY_ORDERS__CART__REMOVE_PRODUCT_REQUEST",
  MY_ORDERS__CART__REMOVE_PRODUCT_SUCCESS =
    "MY_ORDERS__CART__REMOVE_PRODUCT_SUCCESS",
  MY_ORDERS__CART__REMOVE_PRODUCT_FAILURE =
    "MY_ORDERS__CART__REMOVE_PRODUCT_FAILURE",
  MY_ORDERS__CART__CHECKOUT_PRODUCT_REQUEST =
    "MY_ORDERS__CART__CHECKOUT_PRODUCT_REQUEST",
  MY_ORDERS__CART__CHECKOUT_PRODUCT_SUCCESS =
    "MY_ORDERS__CART__CHECKOUT_PRODUCT_SUCCESS",
  MY_ORDERS__CART__CHECKOUT_PRODUCT_FAILURE =
    "MY_ORDERS__CART__CHECKOUT_PRODUCT_FAILURE",
  MY_ORDERS__CART__CANCEL_CHECKEDOUT_PRODUCT_SUCCESS =
    "MY_ORDERS__CART__CANCEL_CHECKEDOUT_PRODUCT_SUCCESS",
  MY_ORDERS__WISHLIST__ADD_PRODUCT_REQUEST =
    "MY_ORDERS__WISHLIST__ADD_PRODUCT_REQUEST",
  MY_ORDERS__WISHLIST__ADD_PRODUCT_SUCCESS =
    "MY_ORDERS__WISHLIST__ADD_PRODUCT_SUCCESS",
  MY_ORDERS__WISHLIST__ADD_PRODUCT_FAILURE =
    "MY_ORDERS__WISHLIST__ADD_PRODUCT_FAILURE",
  MY_ORDERS__WISHLIST__GET_ALL_PRODUCTS_REQUEST =
    "MY_ORDERS__WISHLIST__GET_ALL_PRODUCTS_REQUEST",
  MY_ORDERS__WISHLIST__GET_ALL_PRODUCTS_SUCCESS =
    "MY_ORDERS__WISHLIST__GET_ALL_PRODUCTS_SUCCESS",
  MY_ORDERS__WISHLIST__GET_ALL_PRODUCTS_FAILURE =
    "MY_ORDERS__WISHLIST__GET_ALL_PRODUCTS_FAILURE",
  MY_ORDERS__WISHLIST__REMOVE_PRODUCT_REQUEST =
    "MY_ORDERS__WISHLIST__REMOVE_PRODUCT_REQUEST",
  MY_ORDERS__WISHLIST__REMOVE_PRODUCT_SUCCESS =
    "MY_ORDERS__WISHLIST__REMOVE_PRODUCT_SUCCESS",
  MY_ORDERS__WISHLIST__REMOVE_PRODUCT_FAILURE =
    "MY_ORDERS__WISHLIST__REMOVE_PRODUCT_FAILURE",
  MY_ORDERS__CURRENT_ORDERS__CANCEL_CURRENT_ORDER_REQUEST =
    "MY_ORDERS__CURRENT_ORDERS__CANCEL_CURRENT_ORDER_REQUEST",
  MY_ORDERS__CURRENT_ORDERS__CANCEL_CURRENT_ORDER_SUCCESS =
    "MY_ORDERS__CURRENT_ORDERS__CANCEL_CURRENT_ORDER_SUCCESS",
  MY_ORDERS__CURRENT_ORDERS__CANCEL_CURRENT_ORDER_FAILURE =
    "MY_ORDERS__CURRENT_ORDERS__CANCEL_CURRENT_ORDER_FAILURE";
