export default {
	USER_PROFILE_UPDATE_SUCCESS: "USER_PROFILE_UPDATE_SUCCESS",
	USER_PROFILE_UPDATE_FAILURE: "USER_PROFILE_UPDATE_FAILURE",
	USER_PROFILE_UPDATE_MOBILE_NUMBER: "USER_PROFILE_UPDATE_MOBILE_NUMBER",
};
