// export const PRODUCT_ADD_TO_WISHLIST = "PRODUCT_ADD_TO_WISHLIST";
// export const PRODUCT_ADD_TO_CART = "PRODUCT_ADD_TO_CART";

export const USER_REGISTRATION_REQUEST = "USER_REGISTRATION_REQUEST";
export const USER_REGISTRATION_SUCCESS = "USER_REGISTRATION_SUCCESS";
export const USER_REGISTRATION_FAILURE = "USER_REGISTRATION_FAILURE";

export const USER_REGISTRATION_CHECK_EMAIL_EXISTENCE_REQUEST =
	"USER_REGISTRATION_CHECK_EMAIL_EXISTENCE_REQUEST";
export const USER_REGISTRATION_CHECK_EMAIL_EXISTENCE_SUCCESS =
	"USER_REGISTRATION_CHECK_EMAIL_EXISTENCE_SUCCESS";
export const USER_REGISTRATION_CHECK_EMAIL_EXISTENCE_FAILURE =
	"USER_REGISTRATION_CHECK_EMAIL_EXISTENCE_FAILURE";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";

export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_DELETE_ERROR_VALUE = "USER_DELETE_ERROR_VALUE";

export const USER_PROFILE_UPDATE_REQUEST = "USER_PROFILE_UPDATE_REQUEST";
export const USER_PROFILE_UPDATE_SUCCESS = "USER_PROFILE_UPDATE_SUCCESS";
export const USER_PROFILE_UPDATE_FAILURE = "USER_PROFILE_UPDATE_FAILURE";

export const USER_SIGNUP_STATUS_UPDATE = "USER_SIGNUP_STATUS_UPDATE";
export const USER_SMS_OTP_SENT = "USER_SMS_OTP_SENT";
export const USER_UPDATE_TOKEN = "USER_UPDATE_TOKEN";
export const FORGOT_PASSWORD_INITIATED_SUCCESS =
	"FORGOT_PASSWORD_INITIATED_SUCCESS";
export const USER_PROFILE_UPDATE = "USER_PROFILE_UPDATE";

export const USER_PROFILE_DATA_UPDATE_REQUEST =
	"USER_PROFILE_DATA_UPDATE_REQUEST";
export const USER_PROFILE_DATA_UPDATE_SUCCESS =
	"USER_PROFILE_DATA_UPDATE_SUCCESS";
export const USER_PROFILE_DATA_UPDATE_FAILURE =
	"USER_PROFILE_DATA_UPDATE_FAILURE";
export const USER_PROFILE_CLEAR_DATA_AFTER_SUCCESSFULL_SIGNUP_VERIFICATION =
	"USER_PROFILE_CLEAR_DATA_AFTER_SUCCESSFULL_SIGNUP_VERIFICATION";
// export const PRODUCT_VIEW_ONCLICK_REQUEST = "PRODUCT_VIEW_ONCLICK_REQUEST";
// export const PRODUCT_VIEW_ONCLICK_SUCCESS = "PRODUCT_VIEW_ONCLICK_SUCCESS";
// export const PRODUCT_VIEW_ONCLICK_FAILURE = "PRODUCT_VIEW_ONCLICK_FAILURE";

// export const PRODUCTS_FETCH_REQUEST = "PRODUCTS_FETCH_REQUEST";
// export const PRODUCTS_FETCH_SUCCESS = "PRODUCTS_FETCH_SUCCESS";
// export const PRODUCTS_FETCH_FAILURE = "PRODUCTS_FETCH_FAILURE";
export const USER_DATA_SET_FAILURE = "USER_DATA_SET_FAILURE";
export const USER_DATA_SET_REQUEST = "USER_DATA_SET_REQUEST";
export const USER_DATA_SET_SUCCESS = "USER_DATA_SET_SUCCESS";

export const USER_DATA_UPDATE_REQUEST = "USER_DATA_UPDATE_REQUEST";
export const USER_DATA_UPDATE_SUCCESS = "USER_DATA_UPDATE_SUCCESS";
export const USER_DATA_UPDATE_FAILURE = "USER_DATA_UPDATE_FAILURE";
