export const UPLOADS_PAGE__FETCH_ALL_ADDS_REQUEST =
  "UPLOADS_PAGE__FETCH_ADDS_REQUEST";
export const UPLOADS_PAGE__FETCH_ALL_ADDS_SUCCESS =
  "UPLOADS_PAGE__FETCH_ADDS_SUCCESS";
export const UPLOADS_PAGE__FETCH_ALL_ADDS_FAILURE =
    "UPLOADS_PAGE__FETCH_ADDS_FAILURE",
  UPLOADS_PAGE__CHANGE_PRODUCT_RENT_STATUS_REQUEST =
    "UPLOADS_PAGE__CHANGE_PRODUCT_RENT_STATUS_REQUEST",
  UPLOADS_PAGE__CHANGE_PRODUCT_RENT_STATUS_SUCCESS =
    "UPLOADS_PAGE__CHANGE_PRODUCT_RENT_STATUS_SUCCESS",
  UPLOADS_PAGE__CHANGE_PRODUCT_RENT_STATUS_FAILURE =
    "UPLOADS_PAGE__CHANGE_PRODUCT_RENT_STATUS_FAILURE",
  UPLOADS_PAGE__UPLOAD_ADD_REQUEST = "UPLOADS_PAGE__UPLOAD_ADD_REQUEST",
  UPLOADS_PAGE__UPLOAD_ADD_SUCCESS = "UPLOADS_PAGE__UPLOAD_ADD_SUCCESS",
  UPLOADS_PAGE__UPLOAD_ADD_FAILURE = "UPLOADS_PAGE__UPLOAD_ADD_FAILURE",
  UPLOADS_PAGE__RESET_NEW_ADD_UPLOAD_STATUS =
    "UPLOADS_PAGE__RESET_NEW_ADD_UPLOAD_STATUS",
  UPLOADS_PAGE__GET_PRODUCT_RENTEE_USER_INFO_REQUEST =
    "UPLOADS_PAGE__GET_PRODUCT_RENTEE_USER_INFO_REQUEST",
  UPLOADS_PAGE__GET_PRODUCT_RENTEE_USER_INFO_SUCCESS =
    "UPLOADS_PAGE__GET_PRODUCT_RENTEE_USER_INFO_SUCCESS",
  UPLOADS_PAGE__GET_PRODUCT_RENTEE_USER_INFO_FAILURE =
    "UPLOADS_PAGE__GET_PRODUCT_RENTEE_USER_INFO_FAILURE";
